version: '3'
services:
  topo-fuzz: 
    platform: linux/amd64
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
      - build_mode=interested
      - frr_check=false
      - nproc=16
      - proxy=114.212.85.76:9981
    init: true
    privileged: true
    user: frr
    working_dir: /home/frr/topo-fuzz
    volumes: 
    - type: bind
      source: /lib/modules
      target: /lib/modules

    - type: bind
      source: ../
      target: /home/frr/topo-fuzz

  topo-fuzz-dev:
      platform: linux/amd64
      build:
        context: ../
        dockerfile: ./docker/Dockerfile.dev
        args:
        - build_mode=interested
        - frr_check=false
        - nproc=16
        - proxy=114.212.85.76:9981
      init: true
      privileged: true
      user: root
      working_dir: /home/frr/
      ports:
        - "7100:33"
      volumes: 
        - type: bind
          source: /lib/modules
          target: /lib/modules
        - topo-fuzz-data:/home/frr


#  topo-fuzz-dev-root:
#      platform: linux/amd64
#      build:
#        context: ../
#        dockerfile: ./docker/Dockerfile.root.dev
#        args:
#        - build_mode=interested
#        - frr_check=false
#        - nproc=16
#        - proxy=114.212.85.76:9981
#      init: true
#      privileged: true
#      user: root
#      working_dir: /home/frr/
#      ports:
#        - "7100:33"
#      volumes:
#        - type: bind
#          source: /lib/modules
#          target: /lib/modules
#        - topo-fuzz-data-root:/home/frr

volumes:
  topo-fuzz-data:
  topo-fuzz-data-root: