version: '3'
services:
  topo-fuzz: 
    #platform: linux/amd64
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
      - build_mode=interested
      - frr_check=false
      - nproc=16
      - proxy=http://114.212.83.50:7890
    init: true
    privileged: true
    user: frr
    working_dir: /home/frr/topo-fuzz
    volumes: 
    - type: bind
      source: /lib/modules
      target: /lib/modules

    - type: bind
      source: ../
      target: /home/frr/topo-fuzz

  topo-fuzz-dev:
      #platform: linux/amd64
      build:
        context: ../
        dockerfile: ./docker/Dockerfile.dev
        args:
        - build_mode=interested
        - frr_check=false
        - nproc=16
        - proxy=http://114.212.81.160:7890
      ulimits:
        nofile:
          soft: 2048  # Soft limit
          hard: 4096  # Hard limit
      init: true
      privileged: true
      user: root
      working_dir: /home/frr/
      ports:
        - "7100:33"
      volumes: 
        - type: bind
          source: /lib/modules
          target: /lib/modules
        - type: bind
          source: ../
          target: /home/frr/topo-fuzz