version: '3'
services:
  topo-fuzz:  # Web应用程序服务
    platform: linux/amd64
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
      - build_mode=interested
      - frr_check=false
      - nproc=16
      - proxy=114.212.85.76:9981
    init: true
    privileged: true
    user: frr
    working_dir: /home/frr/topo-fuzz
    volumes: 
    - type: bind
      source: /lib/modules
      target: /lib/modules
