ARG UBUNTU_VERSION=22.04
FROM ubuntu:$UBUNTU_VERSION

ARG DEBIAN_FRONTEND=noninteractive
ENV APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn
ARG proxy
ENV https_proxy $proxy

RUN echo $https_proxy
# Update and install build requirements.
RUN apt update && apt upgrade -y && \
    # Basic build requirements from documentation
    apt-get install -y \
    curl \
    autoconf \
    automake \
    bison \
    build-essential \
    flex \
    git \
    install-info \
    libc-ares-dev \
    libcap-dev \
    libelf-dev \
    libjson-c-dev \
    libpam0g-dev \
    libreadline-dev \
    libsnmp-dev \
    libsqlite3-dev \
    libtool \
    make \
    perl \
    pkg-config \
    python3-dev \
    python3-sphinx \
    texinfo \
    && \
    # Protobuf build requirements
    apt-get install -y \
    libprotobuf-c-dev \
    protobuf-c-compiler \
    && \
    # Libyang2 extra build requirements
    apt-get install -y \
    cmake \
    libpcre2-dev \
    && \
    # Runtime/triage/testing requirements
    apt-get install -y \
    curl \
    gdb \
    iproute2 \
    iputils-ping \
    liblua5.3-dev \
    libssl-dev \
    lua5.3 \
    net-tools \
    python2 \
    python3-pip \
    snmp \
    snmp-mibs-downloader \
    snmpd \
    sudo \
    time \
    tshark \
    valgrind \
    yodl \
    && \
    download-mibs && \
    wget https://raw.githubusercontent.com/FRRouting/frr-mibs/main/iana/IANA-IPPM-METRICS-REGISTRY-MIB -O /usr/share/snmp/mibs/iana/IANA-IPPM-METRICS-REGISTRY-MIB && \
    wget https://raw.githubusercontent.com/FRRouting/frr-mibs/main/ietf/SNMPv2-PDU -O /usr/share/snmp/mibs/ietf/SNMPv2-PDU && \
    wget https://raw.githubusercontent.com/FRRouting/frr-mibs/main/ietf/IPATM-IPMC-MIB -O /usr/share/snmp/mibs/ietf/IPATM-IPMC-MIB && \
    curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output /tmp/get-pip.py && \
    python2 /tmp/get-pip.py && \
    rm -f  /tmp/get-pip.py && \
    python3 -m pip install wheel && \
    python3 -m pip install pytest && \
    python3 -m pip install pytest-sugar && \
    python3 -m pip install pytest-xdist && \
    python3 -m pip install "scapy>=2.4.2" && \
    python3 -m pip install xmltodict && \
    python3 -m pip install grpcio grpcio-tools && \
    python2 -m pip install 'exabgp<4.0.0'

RUN apt-get install -y clang

RUN groupadd -r -g 92 frr && \
    groupadd -r -g 85 frrvty && \
    adduser --system --ingroup frr --home /home/frr \
    --gecos "FRR suite" --shell /bin/bash frr && \
    usermod -a -G frrvty frr && \
    useradd -d /var/run/exabgp/ -s /bin/false exabgp && \
    echo 'frr ALL = NOPASSWD: ALL' | tee /etc/sudoers.d/frr && \
    mkdir -p /home/frr && chown frr.frr /home/frr

RUN echo 'frr:frr' | chpasswd

USER frr:frr

# build and install libyang2
RUN cd && pwd && ls -al && \
    git clone https://github.com/CESNET/libyang.git 

RUN cd && pwd && ls -al && git clone https://github.com/Shbinging/frr.git

RUN cd /home/frr/frr && \
    git fetch --all && \
    git checkout -b fuzz_isis origin/fuzz_isis

 RUN cd /home/frr/libyang && \
    git checkout v2.0.0 && \
    mkdir build; cd build && \
    cmake -DBUILD_SHARED_LIBS=ON -DENABLE_LYD_PRIV=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr \
    -D CMAKE_BUILD_TYPE:String="Release" .. && \
    make -j$(nproc) && \
    sudo make install


#download frr source code


#checkout frr to interested commit


#build and install frr to /usr/lib/frr
RUN cd /home/frr/frr && \
    sh build_fuzzing.sh




#copy docker-start
COPY docker/docker-start /usr/sbin/docker-start



CMD ["/usr/sbin/docker-start"]




#for dev
USER root

RUN apt-get install -y lcov llvm
#COPY docker/requirements.txt /home/frr/py/requirements.txt

#RUN pip3 install -r /home/frr/py/requirements.txt
RUN echo 'root:frr' | chpasswd
RUN usermod -a -G frrvty root
RUN usermod -a -G frr root && chown :frr /home/frr



